DATABASE_URL='jdbc:mysql://localhost:3306/stock'
DATABASE_USER='root'
DATABASE_PASSWORD='cloudera'
HOST_NAME='localhost'
DATABSE_USER_PASS_FILE='database_cred'
PORT='3306'
MYSQL_CON='mysql://root:cloudera@localhost:3306/stock'
TOEMAIL='bigdatatrunk@gmail.com'
